// app/data.js
export const HERO_SLIDES = [
  {
    img: "/hero-1.jpg",
    label: "Merzouga · Erg Chebbi — Sahara Desert, Morocco",
  },
  { img: "/hero-2.jpg", label: "Chefchaouen · The Blue Pearl of the Rif" },
  { img: "/hero-3.jpg", label: "Draa Valley · Ancient Kasbahs at Dusk" },
  { img: "/hero-4.jpg", label: "Sahara · Golden Dune Ridges at Sunset" },
];

export const DESTINATIONS = [
  {
    id: "marrakech",
    num: "01",
    name: "Marrakech",
    tagline: "The Red City · Imperial Heart",
    heading: "Where every hidden door leads somewhere extraordinary.",
    lede: "Lose yourself in the ochre labyrinth of Marrakech's ancient medina — a UNESCO World Heritage site where Jemaa el-Fnaa pulses with storytellers at dusk and saffron perfumes the morning air. Our private Marrakech excursions go beyond the surface: artisan workshops only locals know, rooftop dinners above the sea of minarets, and sunrise visits to sacred sites before the crowds arrive.",
    img: "https://images.unsplash.com/photo-1570133435573-fcb96d98f69b?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    badge: "Heritage",
    days: "5 days",
    price: "1,290",
    highlights: [
      {
        t: "Jemaa el-Fnaa",
        s: "Private evening with storytellers & gastronomy",
      },
      { t: "Majorelle Garden", s: "Yves Saint Laurent's living legacy" },
      { t: "Private Riad Stay", s: "Hand-selected hidden courtyards" },
      { t: "Bahia Palace", s: "Moorish architecture — after hours" },
    ],
  },
  {
    id: "ouarzazate",
    num: "02",
    name: "Ouarzazate",
    tagline: "Gateway to the Sahara · Desert Kingdom",
    heading: "Where the Sahara reveals itself, one dune at a time.",
    lede: "Cross the High Atlas and descend into the ancient Draa Valley, where kasbahs rise from desert rock and the horizon dissolves into eternity. Your Sahara desert tour leads to Erg Chebbi's towering golden dunes — where a luxury tented camp awaits beneath ten thousand stars, and a silence so complete you will hear your own heartbeat. This is the Morocco people come back for.",
    img: "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?auto=format&fit=crop&w=1400&q=80",
    badge: "Desert",
    days: "7 days",
    price: "1,680",
    highlights: [
      { t: "Aït Benhaddou", s: "UNESCO ksar — private guided access" },
      { t: "Erg Chebbi Dunes", s: "Dawn camel expedition into the Sahara" },
      { t: "Luxury Desert Camp", s: "Canopy beds, chef, open sky" },
      { t: "Atlas Studios", s: "Where Lawrence of Arabia was filmed" },
    ],
  },
  {
    id: "fez",
    num: "03",
    name: "Fez",
    tagline: "Imperial Soul · 12 Centuries of Living Craft",
    heading: "A medieval city that never stopped breathing.",
    lede: "Founded in 859 AD, Fez el-Bali is the world's largest car-free urban area — a living museum where the craft of blue pottery, hammered brass, and hand-stitched leather is passed down in the same workshops it always has been. Walk with our master guides past tanneries that run on pomegranate and saffron, into madrasas of geometric perfection, and through private homes where centuries of stories wait to be shared.",
    img: "https://images.unsplash.com/photo-1557503799-fac6a98054b3?q=80&w=1586&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    badge: "Culture",
    days: "4 days",
    price: "1,140",
    highlights: [
      { t: "Chouara Tanneries", s: "Private rooftop access — no crowds" },
      { t: "Al-Attarine Madrasa", s: "The Marinid dynasty's masterpiece" },
      {
        t: "Artisan Workshops",
        s: "Zellige, brass & leather — meet the masters",
      },
      { t: "Bab Boujloud", s: "The Blue Gate — medina's living entrance" },
    ],
  },
  {
    id: "tangier",
    num: "04",
    name: "Tangier",
    tagline: "Where Africa Meets Europe · The Literary Edge",
    heading: "Africa's most seductive port, endlessly rewriting itself.",
    lede: "Perched at the tip of the African continent, where the Atlantic surrenders to the Mediterranean, Tangier has drawn painters, poets, and seekers for centuries. Paul Bowles wrote here. Matisse painted here. Cafés overlook the strait; whitewashed kasbahs tumble toward a sapphire sea. Come for the history, stay for the feeling you can't quite name.",
    img: "https://images.unsplash.com/photo-1564507004663-b6dfb3c824d5?q=80&w=1548&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    badge: "Coastal",
    days: "3 days",
    price: "890",
    highlights: [
      { t: "Café Hafa", s: "Sunset over the Strait of Gibraltar" },
      { t: "Kasbah Museum", s: "Andalusian gardens & maritime history" },
      { t: "Cap Spartel", s: "The exact point two oceans meet" },
      { t: "Grand Socco", s: "The great market, unchanged for centuries" },
    ],
  },
  {
    id: "agadir",
    num: "05",
    name: "Agadir",
    tagline: "Atlantic Shore · Where Morocco Breathes Free",
    heading: "Sun, surf, and a Morocco most visitors never reach.",
    lede: "Beyond Agadir's ten-kilometre crescent of golden beach, the real south reveals itself: argan groves tended by women's cooperatives producing liquid gold, Souss-Massa lagoons turning pink with flamingos at dusk, and the Anti-Atlas foothills rising above it all. Surf the Atlantic breaks at Taghazout, walk Paradise Valley's palm oasis, and discover the Morocco that belongs to no postcard.",
    img: "https://images.unsplash.com/photo-1630172006681-a0b1d335c9e3?q=80&w=1548&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    badge: "Seaside",
    days: "5 days",
    price: "1,220",
    highlights: [
      { t: "Taghazout Surf", s: "Morocco's world-famous Atlantic breaks" },
      { t: "Argan Cooperative", s: "Women-led heritage, liquid gold" },
      { t: "Souss-Massa Park", s: "Flamingos, ibis & coastal wilderness" },
      { t: "Paradise Valley", s: "Hidden palm oasis — off the tourist trail" },
    ],
  },
];

export const PACKAGES = [
  // DESERT
  {
    id: 1,
    cat: "Desert",
    title: "Sahara by Moonlight",
    route: "Marrakech · Ouarzazate · Merzouga",
    duration: "7 Days",
    price: "1,890",
    rating: 5.0,
    reviews: 186,
    img: "https://images.unsplash.com/photo-1549140600-78c9b8275e9d?q=80&w=774&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    desc: "Seven days from Marrakech’s medina to Erg Chebbi’s golden heart — crossing the High Atlas, the cinematic Draa Valley, and arriving at a luxury desert camp beneath the Milky Way. Camel treks at dawn, Berber tagine over open coals, and a silence so profound it stays with you long after you leave.",
  },
  {
    id: 2,
    cat: "Desert",
    title: "Erg Chigaga: Morocco’s Last Frontier",
    route: "Zagora · M’Hamid · Erg Chigaga",
    duration: "6 Days",
    price: "1,720",
    rating: 4.9,
    reviews: 58,
    img: "https://images.unsplash.com/photo-1737927427538-9f9b4ea4ab02?q=80&w=2062&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    desc: "Fewer than 2% of Morocco visitors ever reach Erg Chigaga. This 6-day 4x4 expedition crosses nomad territory, wadi canyons, and lunar plateaux to reach Morocco’s most remote dune sea — where a luxury wilderness camp sits beyond the edge of the map. Pure, unfiltered Sahara.",
  },
  {
    id: 3,
    cat: "Desert",
    title: "The Draa Valley Odyssey",
    route: "Ouarzazate · Draa Valley · Merzouga",
    duration: "5 Days",
    price: "1,450",
    rating: 4.8,
    reviews: 73,
    img: "https://images.unsplash.com/photo-1714229519448-bd6818424912?q=80&w=1738&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    desc: "Follow the ancient caravan route through 100,000 palms and mud-brick kasbahs, past Berber villages and rose-filled valleys, to the Sahara’s edge at Merzouga. Five days of Morocco’s most cinematic landscapes — ending with a desert sunset that will rearrange your understanding of colour.",
  },

  // MOUNTAINS
  {
    id: 4,
    cat: "Mountains",
    title: "High Atlas Immersion",
    route: "Marrakech · Imlil · Toubkal",
    duration: "5 Days",
    price: "1,320",
    rating: 4.9,
    reviews: 142,
    img: "https://images.unsplash.com/photo-1559315390-1065ae6b47c0?q=80&w=2988&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    desc: "Five days deep in the High Atlas — Berber villages, mountain passes, and walks through walnut groves far from any tourist trail. Stay in family guesthouses where dinner is cooked on wood fires and the conversation flows in three languages. The mountains reveal a Morocco few ever see.",
  },
  {
    id: 5,
    cat: "Mountains",
    title: "Toubkal Summit Trek",
    route: "Imlil · Refuge · Mount Toubkal",
    duration: "4 Days",
    price: "1,100",
    rating: 4.9,
    reviews: 96,
    img: "https://images.unsplash.com/photo-1738412349443-359e6935422d?q=80&w=2064&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    desc: "North Africa’s highest peak at 4,167m. In four days, our expert mountain guides lead you from the walnut groves of Imlil to a summit where Morocco unfolds in every direction — Sahara to the south, Atlantic glitter to the west. The hardest part isn’t the climb. It’s leaving.",
  },
  {
    id: 6,
    cat: "Mountains",
    title: "Ourika Valley Escape",
    route: "Marrakech · Ourika · Setti Fatma",
    duration: "3 Days",
    price: "640",
    rating: 4.7,
    reviews: 89,
    img: "https://images.unsplash.com/photo-1671804079626-4aaafa95184e?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    desc: "Just 35km from Marrakech, the Ourika Valley feels like another world — a lush green canyon where waterfalls cascade into cold pools and saffron fields perfume the mountain air. Three days of Berber warmth, honest food, and a landscape that cures everything the city exhausted in you.",
  },

  // CULTURE
  // {
  //   id: 7,
  //   cat: "Culture",
  //   title: "Artisan's Morocco",
  //   route: "Fez · Meknes · Chefchaouen",
  //   duration: "8 Days",
  //   price: "2,120",
  //   rating: 5.0,
  //   reviews: 76,
  //   img: "https://images.unsplash.com/photo-1577535387542-3c13cf20e40e?auto=format&fit=crop&w=900&q=80",
  //   desc: "Meet master craftsmen and explore Morocco’s rich artistic traditions and heritage cities.",
  // },
  // {
  //   id: 8,
  //   cat: "Culture",
  //   title: "Imperial Heritage Tour",
  //   route: "Rabat · Fez · Marrakech",
  //   duration: "7 Days",
  //   price: "1,980",
  //   rating: 4.9,
  //   reviews: 132,
  //   img: "https://images.pexels.com/photos/3889855/pexels-photo-3889855.jpeg?auto=compress&cs=tinysrgb&w=900",
  //   desc: "Discover Morocco’s imperial cities, historic medinas, and architectural treasures.",
  // },
  // {
  //   id: 9,
  //   cat: "Culture",
  //   title: "Medinas & Traditions",
  //   route: "Casablanca · Fez · Marrakech",
  //   duration: "6 Days",
  //   price: "1,650",
  //   rating: 4.8,
  //   reviews: 101,
  //   img: "https://images.unsplash.com/photo-1597212618440-806262de4f6b?auto=format&fit=crop&w=900&q=80",
  //   desc: "Dive into vibrant souks, traditional cuisine, and centuries-old Moroccan culture.",
  // },
];

export const TESTIMONIALS = [
  {
    quote:
      "We had been to Morocco before — independently — and missed everything. Within the first hour this time, our guide had us in a private riad courtyard drinking argan-oil coffee with the owner&apos;s family. The whole trip was like that: <em>doors opened, tables extended, moments you could never manufacture.</em> We&apos;ve already sent twelve friends their way.",
    name: "Elena & Marc Dufresne",
    loc: "Paris, France",
    avatar:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80",
    img: "https://images.unsplash.com/photo-1597212618440-806262de4f6b?auto=format&fit=crop&w=1000&q=80",
  },
  {
    quote:
      "I have stayed in seven-star hotels and camped in Patagonia. The Sahara camp Morocco Tours arranged was unlike either — a luxury that understood exactly what the desert demands: silence, heat, a sky full of stars, and one extraordinary meal cooked over open coals. <em>I have already been back once. I will go again.</em>",
    name: "Hiroshi Tanaka",
    loc: "Tokyo, Japan",
    avatar:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80",
    img: "https://images.unsplash.com/photo-1489573280374-2e193c63726c?q=80&w=1740&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    quote:
      "I mentioned once, in passing, that it was our anniversary. I didn&apos;t expect them to do anything with that. But in the middle of the Sahara — three hours from the nearest town — they had arranged rose petals, a musician playing oud by lamplight, and pastilla prepared from scratch. <em>My wife still isn&apos;t sure it was real.</em> We&apos;re already planning our return.",
    name: "James Whitfield",
    loc: "London, UK",
    avatar:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80",
    img: "https://images.unsplash.com/photo-1580746738099-1cb74f972feb?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];
